### PR TITLE
all about programming

### PR DESCRIPTION
**Pull request by manideepami**
Adding a resource to the blog where it updates programming related articles

### CODE REVIEW

**Comment by skbly7** [comment]
Sorry, but the resource isn't related to the topic of the repository. Rejecting the pull request.

**Comment by manideepami** [comment]
This is related. Kindly add it

**Comment by skbly7** [comment]
It is not related!

**Comment by vicky002** [comment]
There are many blogs related to programming. It is not related to CodeChef resources.

**Pull request closed without merging**
