### PR TITLE
add reference to DS with Java

### PR DESCRIPTION
**Pull request by CuriousNikhil**
A reference added for the data structure implementations in java.

### CODE REVIEW

**Review by vicky002 — APPROVED** [review]
Looks good to me. ✔️

**Comment by CuriousNikhil** [comment]
Thanks a lot !!

**Comment by ghost** [comment]
https://www.udemy.com/course/learn-data-structure-algorithms-with-java-interview/

This lecture is very useful for your topic.

**Comment by CuriousNikhil** [comment]
Please merge this. If it's good to go.

**Comment by ghost** [comment]
Sir i'm very new to github so i seem to be unaware of the merge mechanism.
Your help is much appreciated.

**Pull request closed without merging**
